### PR TITLE
Serve front-end files #71 Can now access front-end components on the …

### LINKED ISSUE #71: Add line to serve front-end files on express erver
Serve the files in 'Front-End' statically.
Expected outcome: be able to access all front-end components on the server for testing

### PR DESCRIPTION
**Pull request by ginpks**
Added a line to allow access to front-end files on the server for testing.

### CODE REVIEW

**Review by sheyanyu — CHANGES_REQUESTED** [review]
Since the server.js file is in the Back-End folder and the Front-End folder is parallel to it, maybe we need to update the path for serving static files?

**Comment by ginpks** [comment]
> Since the server.js file is in the Back-End folder and the Front-End folder is parallel to it, maybe we need to update the path for serving static files?

How do you suggest we update the path? If we direct users to this link http://localhost:3000/login/LoginPage.html once the express server is running, then it should be fine since every front-end component is accessible from then onwards

**Comment by sheyanyu** [comment]
> > Since the server.js file is in the Back-End folder and the Front-End folder is parallel to it, maybe we need to update the path for serving static files?
> 
> How do you suggest we update the path? If we direct users to this link http://localhost:3000/login/LoginPage.html once the express server is running, then it should be fine since every front-end component is accessible from then onwards

ah that makes sense. yea I think current one would be fine. (I will try to figure out how to approve this ;-;

**Review by sheyanyu — APPROVED** [review]
GTG!

**Pull request merged**
